
### 
GET http://localhost:8080/doctor/getAllhoso

###  phan phieu kham
GET http://localhost:8080/doctor/getPhieukham/null
Authorization: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7InVzZXJJZCI6IjY3MWE4NWM0MzEzNTQzOWExNThmNTE5OSIsImVtYWlsIjoiYmFjc2lkdXlAZXhhbXBsZS5jb20iLCJyb2xlIjoiQlMiLCJhY3RpdmUiOnRydWUsImNyZWF0ZWRBdCI6IjIwMjQtMTEtMDdUMDk6MzU6NTUuMzY0WiJ9LCJpYXQiOjE3MzA5NzIxNTUsImV4cCI6MTczMTA1ODU1NX0.k4_kUUCZKLhjIS5PFU2ynbKbLfj72OVnOqPKH06ix7c"
###
GET http://localhost:8080/doctor/detailPhieukham/671f36b160bffcb192f801ca

###
GET  http://localhost:8080/doctor/thuoc/pa

### Bác sĩ kê xong đơn thuốc và nhấn lưu thuốc
PUT http://localhost:8080/doctor/updatePhieukham/671f36b160bffcb192f801ca
Content-Type: application/json
Authorization: ""
{
  "TrieuChung": "Đau đầu, chóng mặt",
  "ChanDoan": "Thiếu máu",
  "LoiDan": "Uống nhiều nước, nghỉ ngơi",
  "Thuoc": [
    {
      "MaThuoc": "6716190fb5ab976661e442ea",
      "SoLuong": 2,
      "Cachdung": "ăn trước khi uống"
    },
    {
      "MaThuoc": "67207b100b98284bc2f63be4",
      "SoLuong": 2,
      "Cachdung": "ăn trước khi uống"
    }
  ]
}

### xem lich kham
GET http://localhost:8080/doctor/lichlam
Authorization: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7InVzZXJJZCI6IjY3MWE4NWM0MzEzNTQzOWExNThmNTE5OSIsImVtYWlsIjoiYmFjc2lkdXlAZXhhbXBsZS5jb20iLCJyb2xlIjoiQlMiLCJhY3RpdmUiOnRydWUsImNyZWF0ZWRBdCI6IjIwMjQtMTEtMDdUMDg6Mjc6MzEuNjkyWiJ9LCJpYXQiOjE3MzA5NjgwNTEsImV4cCI6MTczMDk3MTY1MX0.BWkxD5YeoRAY3Th67AHQW1A29VMHVhgpORRP6fEhDB4"

